import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Nav from '@/app/components/Nav'
import Header from '@/app/components/Header'
import { ReactNode } from 'react'
import { QueryProvider } from '@/app/providers/QueryProvider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <div className="flex flex-col min-h-screen bg-gray-100">
            <Header />
            <main className="flex-1 overflow-auto px-4 py-2">{children}</main>
            <Nav className="sticky bottom-0" />
          </div>
        </QueryProvider>
      </body>
    </html>
  )
}
