import { Session, User } from 'next-auth'
import { JWT } from 'next-auth/jwt'
import CredentialsProvider from 'next-auth/providers/credentials'

declare module 'next-auth' {
  interface Session {
    jwt?: string
  }
  interface User {
    token: string
  }
}

declare module 'next-auth/jwt' {
  interface JWT {
    jwt: string
    exp: number
  }
}

const decodeJWT = (jwt: string) => {
  const base64Url = jwt.split('.')[1]
  const base64 = base64Url.replace(/-/g, '+').replace(/_/g, '/')
  const jsonPayload = decodeURIComponent(
    atob(base64)
      .split('')
      .map((c) => '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2))
      .join('')
  )

  return JSON.parse(jsonPayload)
}

export const authOptions = {
  providers: [
    CredentialsProvider({
      credentials: {
        email: { label: 'Email', type: 'text' },
        password: { label: 'Password', type: 'password' },
      },
      async authorize(credentials) {
        const response = await fetch(
          `${process.env.NEXT_PUBLIC_API_URL}/login`,
          {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ user: credentials }),
          }
        )

        if (!response.ok) {
          return null
        }

        const { token } = await response.json()
        return { id: '1', token }
      },
    }),
  ],
  callbacks: {
    async jwt({ token, user }: { token: JWT; user: User | undefined }) {
      // When JWT is generated by the backend
      if (user) {
        token.jwt = user.token
        const decodedJWT = decodeJWT(token.jwt)
        if (decodedJWT.exp) {
          token.exp = decodedJWT.exp
        }
      }
      return token
    },
    async session({ session, token }: { session: Session; token: JWT }) {
      session.jwt = token.jwt
      return session
    },
  },
  pages: {
    signIn: '/auth/login',
  },
}

export const publicPages = [
  '/auth/login',
  '/auth/signup',
  '/api/auth/signin',
  '/api/auth/signup',
]
